export const CATEGORIES = [
  { id: '1', name: 'All', icon: 'LayoutGrid' },
  { id: '2', name: 'Burgers', icon: 'Beef' },
  { id: '3', name: 'Pizza', icon: 'Pizza' },
  { id: '4', name: 'Pasta', icon: 'Utensils' },
  { id: '5', name: 'Drinks', icon: 'CupSoda' },
  { id: '6', name: 'Desserts', icon: 'CakeSlice' },
];

export const MENU_ITEMS = [
  {
    id: '1',
    name: 'Supa Truffle Burger',
    category: 'Burgers',
    price: 18.50,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=800&auto=format&fit=crop',
    description: 'Black Angus beef, truffle aioli, caramelized onions, and aged Gruyère.',
  },
  {
    id: '2',
    name: 'Spiced Salmon Poke',
    category: 'All',
    price: 22.00,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
    description: 'Fresh Atlantic salmon, avocado, edamame, and our signature spicy soy dressing.',
  },
  {
    id: '3',
    name: 'Burrata Margherita',
    category: 'Pizza',
    price: 16.00,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=800&auto=format&fit=crop',
    description: 'San Marzano tomatoes, fresh burrata, basil, and extra virgin olive oil.',
  },
  {
    id: '4',
    name: 'Truffle Mac & Cheese',
    category: 'Pasta',
    price: 14.50,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?q=80&w=800&auto=format&fit=crop',
    description: 'Creamy three-cheese sauce, black truffle oil, and a crispy panko topping.',
  },
  {
    id: '5',
    name: 'Passionfruit Mojito',
    category: 'Drinks',
    price: 9.00,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=800&auto=format&fit=crop',
    description: 'Fresh mint, lime, passionfruit puree, and premium white rum.',
  },
  {
    id: '6',
    name: 'Lava Chocolate Cake',
    category: 'Desserts',
    price: 12.00,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?q=80&w=800&auto=format&fit=crop',
    description: 'Warm chocolate cake with a molten center, served with vanilla bean gelato.',
  },
];
